# ---------------------------------------------------------------------------
# TARDISDB
# ---------------------------------------------------------------------------

stages:
    - build
    - test

build_debug:
    stage: build
    script: 
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DTUPLE_STREAM_REQUIRED=true ..
        - ninja
    cache:
        key: "$CI_COMMIT_REF_NAME-debug"
        paths:
            - build/
        policy: pull-push
    artifacts:
        paths:
            - ./build/tester
        expire_in: 1 hrs
    tags:
        - "clang-6.0"
        - "cmake"
        - "python3"

tester:
    stage: test
    script:
        - ./build/tester
    dependencies:
        - build_debug
    tags:
        - "clang-6.0"
        - "llvm-6.0"
        - "cmake"
        - "python3"